[package]
name = "reth-exchange-rates"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
shuttle-rocket = "0.20.0"
shuttle-runtime = "0.20.0"
tokio = "1.26.0"


[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]
